### PR TITLE
News Week Entire project

### PR DESCRIPTION
**Pull request by bertil291utn**
### If you take your time to review I'd be glad to receive feedback.

In this project, I write considerating all requirements for this project 
- Bootstrap for responsive design 
- Styling and position with the same framework 

Thank you 🚀💻

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @bertil291utn . 👨‍🚀  
### Very good job so far.
You follow all the specifications required, the HTML validator doesn't show any error, the readme looks well also the commits and the pull request...👍😄 
To improve your project and make it even better. Kindly check the comments below: 👨‍💻  ⬇️ 
****
- [ ] Blank space between more stories.
From 'md' size to 'xl' size there's a big blank space between the "more stories" section.
On 'md' size the blank space are on the left side.
It makes the page doesn't look good that's why is required this change.
You can add content on that blank space and hide it when it is required using the display bootstrap property.

Screen Shot 2020-03-21 at 3 00 26 PM

Screen Shot 2020-03-21 at 3 00 45 PM

****
- [x] Inline styling.
It isn't permitted the use of inline styling because it is considered a bad practice. 😄 🚫 

Screen Shot 2020-03-21 at 3 05 47 PM


****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by majovanilla** [comment]
Hey @bertil291utn , 👋

## Good job implementing the required changes on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Your page is not complete. You are missing several sections at the end. Please include them in your project and adjust them to be responsive, too.

- Remember your project should be exactly as the original:
Screenshot from 2020-03-21 18-40-07


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version. Some of them you already styled, but some are missing.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Great work implementing the requested changes, 👍 👍  However there is still 1 issue on your layout. 

## Requested changes

- [x] The page should not take up all the view-port on higher resolutions  (see screenshots for reference) If you need to test your project on resolutions higher than your monitor you can use the developer tools on your browser. Please adjust the page to have a margin on left and right on higher resolutions.

Your project on 1080p resolution:

img


Original page on 1080p resolution:

img1

That's all!!  Just a small detail and your project will be ready to go, keep up with the good work!! 🏅 
I would also recommend you to test your projects on resolutions from 250p all the way up to 1080p

After implementing the requested change please re-submit your project for another review.

## Code review by Mario Enrique Delgado Naranjo

**Comment by bertil291utn** [comment]
Hi, @MarioDena Thanks for taking the time to review my changes.
But I can't see any difference. It's same as the original
Cheers
PS. I'll attach SS for the record

### 1080

In this size, it has 30px padding both on the left and on the right for large screen

- **Original**
image

- **My project**
image

### Less than 1080 (md,sm,xs)
In this size, it has 15px padding both on the left and on the right

**My project**
- **768**
image

- **640**
image

**Comment by uryelah** [comment]
Hello **Bertil**, I'm Sarah, your last reviewer for this PR 👩‍🚀 

You guys did an amazing job fixing that one last requirement 🥇 
I also applaud your investment in communicating and document the current state of your project.

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
